config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :samples, only: [:index, :create]
    end
  end

  resources :samples, only: [:index]
  root to: 'samples#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sample.rb
class Sample < ApplicationRecord
  validates_uniqueness_of :capture_time
  validates :capture_time, future: true

  scope :sensor, -> (sensor_id) { where sensor_id: sensor_id }
  scope :time_between, lambda {|start_time, end_time| where("capture_time >= ? AND capture_time <= ?", start_time, end_time )}
  scope :from_time, lambda {|start_time| where("capture_time >= ?", start_time)}
  scope :before_time, lambda {|end_time| where("capture_time <= ?", end_time )}
end

app/controllers/api/v1/samples_controller.rb
module Api
  module V1
    class SamplesController < ApplicationController
      def index
        if params.has_key?(:sensor_id)
          @samples = Sample.sensor(params[:sensor_id])
          @samples = @samples.from_time(params[:start_time]) if params[:start_time].present?
          @samples = @samples.before_time(params[:end_time]) if params[:end_time].present?
          render json: @samples
        else
          render :json => { :errors => 'Params sensor_id is mandatory' }
        end
      end

      def create
        buffer = params[:buffer]
        es = Decoder.new.decode(buffer)
        @samples = es[:entres].each do |e|
          e[:capture_time] = Time.at(e[:capture_time]).to_datetime
          sample = Sample.new(e)
          if sample.save
          else
            ActiveRecord::Base.logger.info "Sample already present in the database #{sample.errors.messages.to_s}"
          end
        end

        render json: @samples ,status: :created
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]

  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_sample
    @sample = Sample.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sample_params
    params.require(:sample).permit(:capture_time, :sensor_id, :light, :soil_moisture, :air_temperature)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parrot</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/samples/_form.html.erb
<%= form_for(sample) do |f| %>
  <% if sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% sample.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :capture_time %>
    <%= f.datetime_select :capture_time %>
  </div>

  <div class="field">
    <%= f.label :sensor_id %>
    <%= f.number_field :sensor_id %>
  </div>

  <div class="field">
    <%= f.label :light %>
    <%= f.number_field :light %>
  </div>

  <div class="field">
    <%= f.label :soil_moisture %>
    <%= f.number_field :soil_moisture %>
  </div>

  <div class="field">
    <%= f.label :air_temperature %>
    <%= f.number_field :air_temperature %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/samples/edit.html.erb
<h1>Editing Sample</h1>

<%= render 'form', sample: @sample %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Samples</h1>

<table>
  <thead>
    <tr>
      <th>Capture time</th>
      <th>Sensor</th>
      <th>Light</th>
      <th>Soil moisture</th>
      <th>Air temperature</th>
    </tr>
  </thead>

  <tbody>
    <% @samples.each do |sample| %>
      <tr>
        <td><%= sample.capture_time %></td>
        <td><%= sample.sensor_id %></td>
        <td><%= sample.light %></td>
        <td><%= sample.soil_moisture %></td>
        <td><%= sample.air_temperature %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/samples/new.html.erb
<h1>New Sample</h1>

<%= render 'form', sample: @sample %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Capture time:</strong>
  <%= @sample.capture_time %>
</p>

<p>
  <strong>Sensor:</strong>
  <%= @sample.sensor_id %>
</p>

<p>
  <strong>Light:</strong>
  <%= @sample.light %>
</p>

<p>
  <strong>Soil moisture:</strong>
  <%= @sample.soil_moisture %>
</p>

<p>
  <strong>Air temperature:</strong>
  <%= @sample.air_temperature %>
</p>

<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>